apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kế thừa từ base
resources:
  - ../../base

# Prefix cho tên resource
namePrefix: dev-

# Labels riêng cho Dev
commonLabels:
  environment: development

# Thay đổi namespace
namespace: kustomize-dev

# Patch: 2 replicas cho Dev
patches:
  - target:
      kind: Deployment
      name: web-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "development"
