apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kế thừa từ base
resources:
  - ../../base

# Prefix cho tên resource
namePrefix: prod-

# Labels riêng cho Prod
commonLabels:
  environment: production

# Thay đổi namespace
namespace: kustomize-prod

# Patch: 5 replicas cho Prod + tăng resources
patches:
  - target:
      kind: Deployment
      name: web-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "production"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
